### ISSUE TITLE
Training on Custom Dataset

### ISSUE THREAD

**Issue by MahdiKoochali** [SysCV/sam-pt#10]
Can you provide a guideline for training on a custom dataset?

**Comment by m43** [comment]
Thank you for your interest in training on a custom dataset. 

We utilize [pre-trained checkpoints](https://github.com/SysCV/sam-pt/blob/228d7cd957d90cbb601b1b6c8ad885f71995a9f3/docs/03-prepare-checkpoints.md) provided by the respective authors for all point trackers and SAM variants. If you're keen on training or fine-tuning the models on a custom point tracking or segmentation dataset, I'd advise delving into PIPS and SAM/HQ-SAM. 

To give you a brief overview:
- PIPS is exclusively trained on the synthetic [FlyingThings++](https://github.com/aharley/pips/blob/486124b4236bb228a20750b496f0fa8aa6343157/README.md#flyingthings-dataset), derived from the FlyingThings optical flow dataset.
- SAM was developed using the expansive [SA-1B dataset](https://github.com/facebookresearch/segment-anything/blob/6fdee8f2727f4506cfbbe553e23b895e27956588/README.md#dataset).
- HQ-SAM training relied on [HQSeg-44K](https://github.com/SysCV/sam-hq/blob/597348543ae88cf8232795df9c741dc9cc6df5b4/train/README.md#1-data-preparation).

I hope this helps guide your efforts!

**Comment by MahdiKoochali** [comment]
Thanks for the quick response.

Regarding your suggestion, in order to fine-tune the sam-pt model, I have to fine-tune both PIPS and SAM(or HQ-SAM) and at last load the obtained checkpoints from both models to run sam-pt, did I get your point?

**Comment by m43** [comment]
Correct, to fine-tune SAM-PT, you'd finetune PIPS or SAM or both

**Comment by MahdiKoochali** [comment]
Thanks for your answer.

Can you also explain which repository did you use to fine-tune the SAM?

**Comment by m43** [comment]
Hej @MahdiKoochali, we rely on the original checkpoints provided by the authors and do not perform additional fine-tuning. For SAM, you can download these checkpoints using the instructions provided [here](https://github.com/SysCV/sam-pt/blob/228d7cd957d90cbb601b1b6c8ad885f71995a9f3/docs/03-prepare-checkpoints.md#sam). Let us know if you need further assistance!

**Comment by MahdiKoochali** [comment]
Thank you so much!

I am trying to use SAM-PT on a custom dataset (in the microscopic image domain). Unfortunately, the results were not satisfying in this domain. Regarding your answer earlier, about fine-tuning, I decided to fine-tune SAM.
I used [micro-sam](https://github.com/computational-cell-analytics/micro-sam) and fine-tuned it, but I got the attached error when I wanted to run SAM-PT with my custom checkpoint.

My suspicion is that this error might stem from an incompatibility issue with the SAM models.

It would be perfect if you help me to solve this error or help me to fine-tune SAM.

![image](https://github.com/SysCV/sam-pt/assets/18505948/349b14fe-6d49-403e-b5d1-7496537687a9)

**Comment by m43** [comment]
Hej, micro-sam uses the same SAM architecture as the original SAM as it uses SAM directly (see [here](https://github.com/computational-cell-analytics/micro-sam/blob/1620d14e80e332ec68172ee9bb2a808bf4c782ae/environment_gpu.yaml#L13) and [here](https://github.com/computational-cell-analytics/micro-sam/blob/1620d14e80e332ec68172ee9bb2a808bf4c782ae/micro_sam/util.py#L192)). Thus, it must be possible to load the state directly into an instance of SAM with `sam_model.load_state_dict(your_model_state)`.

However, the **training** checkpoints in micro-sam might be saved in a peculiar way so that they cannot be directly loaded into SAM. What code have you used to save the checkpoint? You might want to try [this short snippet](https://gist.github.com/m43/cd2173622929593b8aa13100fb8debbe) out that could convert the micro-sam training checkpoint to a normal SAM checkpoint. I didn't have a training checkpoint to test it with, perhaps you could test if it works well on your side. The cleaned `model_state` should look something like `odict_keys(['image_encoder.pos_embed', 'image_encoder.patch_embed.proj.weight', ... ])`.

**Comment by m43** [comment]
On a side note, I'd also suggest you try out different point trackers from the repository for your data. For example, you can try using CoTracker instead of PIPs by adding `model/point_tracker=cotracker model.positive_points_per_mask=16` to the command line arguments.

I'd also suggest you try varying the number of iterative refinement iterations to better tune the parameter to your fine-tuned SAM checkpoint. You can do so by adding and varying the `model.iterative_refinement_iterations=3` command line argument. Cheers!
