### ISSUE TITLE
problem when installing requirements.txt

### ISSUE THREAD

**Issue by Tomtunn** [SysCV/sam-pt#16]
hello this work is this repository is very nice,
however i got some issue when i try to install the requirements.txt
its report this error
`note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for detectron2
  Running setup.py clean for detectron2
Failed to build detectron2
ERROR: Could not build wheels for detectron2, which is required to install pyproject.toml-based projects`

I think that the problem is on the ` git+https://github.com/facebookresearch/detectron2@v0.6`
i try to install manually but its doesn't work either

I'd be grateful for your assistance if you could lend a hand.

**Comment by m43** [comment]
Hej, from your description, it seems like the issue is related to building/installing `detectron2`. I recommend looking into the official [Detectron2 installation documentation](https://detectron2.readthedocs.io/en/v0.6/tutorials/install.html) which provides more details.

If you are not interested in [running the VIS experiments](https://github.com/SysCV/sam-pt/blob/0dcc74782338f912b52bffa317379c90f03161d6/docs/04-running-experiments.md#running-vis-experiments), you might consider skipping the installation of Detectron2 altogether. You can do so by removing `git+https://github.com/facebookresearch/detectron2@v0.6` from `requirements.txt` and re-running `pip install -r requirements.txt`. Without Detectron2, you can still run the demo and/or the VOS experiments.

Otherwise, for us to better assist you, could you please provide the full error logs? It would be helpful to see more details surrounding the error you're encountering. Additionally, can you let us know which operating system you are using?

Hope this helps!
